services:
  user-service:
    build:
      context: ./backend/user-service
    container_name: user-service
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env
    
  order-service:
    build:
      context: ./backend/order-service
    container_name: order-service
    ports:
      - "8001:8000"
    depends_on:
      - user-service

  database:
    image: postgres:16
    container_name: database
    env_file:
      - .env
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

networks:
  default:
    name: test-fastapi
    external: true